import os
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# -----------------------------
# FASTAPI SETUP + CORS ENABLED
# -----------------------------
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # allow all (React, Netlify, Vercel)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -----------------------------
# GLOBAL STORAGE
# -----------------------------
mapping = {}            # college_roll → exam_roll
drive_index = {}        # exam_roll → file info
ROOT_DATA_FOLDER = "data"


# -----------------------------------------------------------
# LOAD ALL EXCEL MAPPINGS (1sem, 3sem, 5sem)
# -----------------------------------------------------------
def load_excel_mappings():
    global mapping
    mapping.clear()

    print("\n==== LOADING EXCEL MAPPINGS ====")

    for filename in os.listdir(ROOT_DATA_FOLDER):
        if filename.endswith(".xlsx") and filename.startswith("mapping_"):
            filepath = os.path.join(ROOT_DATA_FOLDER, filename)

            print(f"[INIT] Loading mapping file: {filepath}")

            df = pd.read_excel(filepath)

            # Auto-detect columns
            detected_college = None
            detected_exam = None

            for col in df.columns:
                name = col.strip().lower()
                if "roll" in name and ("college" in name or "no." in name):
                    detected_college = col
                if "exam" in name:
                    detected_exam = col

            if not detected_college or not detected_exam:
                raise RuntimeError(
                    f"File {filename} is missing required roll/exam columns. Found: {df.columns}"
                )

            print(
                f"[INIT] {filename} → Using Columns: "
                f"College='{detected_college}', Exam='{detected_exam}'"
            )

            for _, row in df.iterrows():
                college_roll = str(row[detected_college]).strip()
                exam_roll = str(row[detected_exam]).strip()

                if college_roll not in mapping:
                    mapping[college_roll] = exam_roll

    print(f"[DONE] Total Mappings Loaded: {len(mapping)}")


# -----------------------------------------------------------
# LOAD DRIVE INDEX (CSV GENERATED BY GOOGLE APP SCRIPT)
# -----------------------------------------------------------
def load_drive_index():
    global drive_index
    drive_index.clear()

    print("\n==== LOADING DRIVE INDEX ====")

    csv_file = os.path.join(ROOT_DATA_FOLDER, "drive_index.csv")

    if not os.path.exists(csv_file):
        raise FileNotFoundError("drive_index.csv is missing!")

    df = pd.read_csv(csv_file)

    required_cols = ["File Name", "File ID", "Path"]
    for col in required_cols:
        if col not in df.columns:
            raise RuntimeError(f"drive_index.csv missing required column: {col}")

    for _, row in df.iterrows():
        file_name = str(row["File Name"])
        file_id = str(row["File ID"])
        path = str(row["Path"])

        exam_roll = file_name.split("_")[0]  # Extract exam roll

        drive_index[exam_roll] = {
            "file_name": file_name,
            "file_id": file_id,
            "path": path.replace("root/", ""),  # clean path
        }

    print(f"[DONE] Drive Files Loaded: {len(drive_index)}")


# -----------------------------------------------------------
# BUILD BOTH INDEXES AT STARTUP
# -----------------------------------------------------------
def build_indexes():
    print("\n==== BUILDING INDEXES ====")
    load_excel_mappings()
    load_drive_index()
    print("==== INDEX BUILD COMPLETE ====\n")


@app.on_event("startup")
def on_startup():
    build_indexes()


# -----------------------------------------------------------
# HEALTH CHECK ENDPOINT
# -----------------------------------------------------------
@app.get("/health")
def health():
    return {
        "status": "ok",
        "mapping_count": len(mapping),
        "file_count": len(drive_index),
    }


# -----------------------------------------------------------
# SEARCH ENDPOINT
# -----------------------------------------------------------
@app.post("/search")
async def search(data: dict):
    roll_no = str(data.get("roll_no", "")).strip()

    if roll_no == "":
        raise HTTPException(status_code=400, detail="Roll number is required")

    if roll_no not in mapping:
        raise HTTPException(status_code=404, detail="College Roll Number not found")

    exam_roll = mapping[roll_no]

    if exam_roll not in drive_index:
        return {
            "college_roll": roll_no,
            "exam_roll": exam_roll,
            "file_name": None,
            "path": None,
            "drive_view_url": None,
            "drive_download_url": None,
            "note": "Exam Roll found but no file uploaded yet."
        }

    file_info = drive_index[exam_roll]
    file_id = file_info["file_id"]

    return {
        "college_roll": roll_no,
        "exam_roll": exam_roll,
        "file_name": file_info["file_name"],
        "path": file_info["path"],
        "drive_view_url": f"https://drive.google.com/file/d/{file_id}/view?usp=drivesdk",
        "drive_download_url": f"https://drive.google.com/uc?export=download&id={file_id}",
        "note": None
    }
